name: Release

on:
  push:
    branches: ["main"]

env:
  BUILD_TYPE: Release
  GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:

#   versioning:
#     name: Semantic Release
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         persist-credentials: false
#     - uses: actions/setup-node@v3
#     - run: cp .github/workflows/package.json . && npm install && npx semantic-release

  build_wheels:
    name: Build Wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
#     needs: versioning
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'      
      - uses: actions/setup-python@v3
      - uses: crazy-max/ghaction-setup-docker@v1.0.0
        with:
          version: 23.0.1
      - uses: docker/setup-qemu-action@v2.1.0

      - name: Install CIBuildWheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel
        
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  
  
  publish_python:
    name: Publish Python
    runs-on: ubuntu-20.04
    needs: build_wheels
    environment:
      name: pypi
      url: https://pypi.org/p/usearch
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: ./dist/

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: ./dist/artifact
          verbose: true
          print_hash: true

  publish_javascript:
    name: Publish JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git submodule update --init --recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm ci
      - run: npm test
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}

  publish_rust:
    name: Publish Rust
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - uses: katyo/publish-crates@v2
      with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}          

  publish_java:
    name: Publish Java
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2    
    - name: Execute Gradle build
      run: gradle clean build
    - name: Publish package
      run: gradle publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_docs:
    name: Deploy Docs
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: publish_python
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'   
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y doxygen graphviz dia git && pip install sphinx breathe furo m2r2 sphinxcontrib-googleanalytics==0.2.dev20220708 sphinxcontrib-jquery
      - name: Install USearch from PyPi
        run: pip install usearch
      - name: Build documentation
        run: cd docs && make html
      - name: Copy assets
        run: cp -r assets build/docs/html/
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "./build/docs/html/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
